//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace heroku.api {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Query {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Query() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("heroku.api.Query", typeof(Query).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///            &quot;detalhes&quot;: [
        ///              {
        ///                &quot;codigo_forca_tarefa&quot;: 27,
        ///                &quot;cdpessoa&quot;: 2525,
        ///                &quot;unidade_prisional&quot;: &quot;PENITENCIÁRIA DE PEDRINHAS - SÃO LUÍS&quot;,
        ///                &quot;tipo_apenado&quot;: &quot;Definitivo&quot;,
        ///                &quot;tipo_servico&quot;: &quot;Ordinário&quot;,
        ///                &quot;relato&quot;: &quot;Lorem ipsum odio mollis convallis platea in, vitae tristique orci pellentesque fringilla cursus hendrerit, ullamcorper rhoncus sit pulvinar tellus. euismod turpis mi erat imperdiet nibh m [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string consulta {
            get {
                return ResourceManager.GetString("consulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///          {
        ///            &quot;notificacoes&quot;: [
        ///              {
        ///                &quot;numero_processo_formatado&quot;: &quot;1920210.202939.229292&quot;,
        ///                &quot;numero_notificacao&quot;: 2525,
        ///                &quot;tipo_notificacao&quot;: &quot;OCTUS&quot;,
        ///                &quot;data_notificacao&quot;: &quot;10/09/2025&quot;
        ///              },
        ///               {
        ///                &quot;numero_processo_formatado&quot;: &quot;1920210.202939.229292&quot;,
        ///                &quot;numero_notificacao&quot;: 2525,
        ///                &quot;tipo_notificacao&quot;: &quot;OCTUS&quot;,
        ///                &quot;data_notificacao&quot;: &quot;10 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string consulta2 {
            get {
                return ResourceManager.GetString("consulta2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///        {
        ///          &quot;unidade_prisional&quot;: [
        ///            {
        ///              &quot;id&quot;: 1,
        ///              &quot;descricao&quot;: &quot;PENITENCIÁRIA DE PEDRINHAS - SÃO LUÍS&quot;
        ///            },
        ///            {
        ///              &quot;id&quot;: 2,
        ///              &quot;descricao&quot;: &quot;PENITENCIÁRIA DE PEDRINHAS 2 - SÃO LUÍS&quot;
        ///            },
        ///            {
        ///              &quot;id&quot;: 3,
        ///              &quot;descricao&quot;: &quot;PENITENCIÁRIA DE PEDRINHAS 3 - SÃO LUÍS&quot;
        ///            }
        ///          ],
        ///          &quot;defensor&quot;: [
        ///            {
        ///              &quot;id&quot;: 1,
        ///              &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string filtro {
            get {
                return ResourceManager.GetString("filtro", resourceCulture);
            }
        }
    }
}
